version: "3"
services:
  stormworks:
    build: .
    ports:
      - "3478:3479"
      - "4379:4379"
      - "4380:4380"
      - "25564:25564"
      - "25565:25565"
      - "25566:25566"
    command: /start_wine.sh
    volumes:
      - ${PWD}/server_config.xml:/home/wine/.wine32/drive_c/users/root/Application Data/Stormworks/server_config.xml
volumes:
  stormworks_config:
